# Generated by Django 3.2.23 on 2024-02-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240205_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
