# Generated by Django 3.2.23 on 2024-02-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='availability',
            field=models.PositiveIntegerField(),
        ),
    ]
