# Generated by Django 3.2.23 on 2024-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ticket_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_specific_field',
            field=models.CharField(default='SOMETHING CUSTOMER', max_length=255),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='organizer_specific_field',
            field=models.CharField(default='something organizer', max_length=255),
        ),
    ]
