# Generated by Django 3.2.23 on 2024-02-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240205_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_specific_field',
        ),
    ]
