# Generated by Django 3.2.23 on 2024-02-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_customer_customer_specific_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorganizer',
            name='organizer_specific_field',
        ),
    ]
