# Generated by Django 3.2.23 on 2024-02-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_eventorganizer_organizer_specific_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_specific_field',
            field=models.CharField(default='SOMETHING CUSTOMER', max_length=255),
        ),
    ]
