# Generated by Django 3.2.23 on 2024-02-06 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer_customer_specific_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='Its a surprise event'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Surprise Event', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Venue pura', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='availability',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.11, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(default='Surprise Ticket xD', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='User Singh Choudhary', max_length=255),
        ),
    ]
