# Generated by Django 3.2.24 on 2024-02-07 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_eventorganizer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eventorganizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
